name: Python Code Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # لم نعد بحاجة لصلاحيات الكتابة
    # permissions:
    #   contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # لا يزال من الجيد تثبيتها هنا لضمان وجودها
          pip install ruff black pytest 

      - name: Run tests
        run: pytest -m "not ui"

      # --- START OF FINAL FIX ---
      # الخطوة الجديدة: الفحص فقط، وليس الإصلاح
      - name: Lint with ruff
        run: ruff check .

      # الخطوة الجديدة: الفحص فقط، وليس التنسيق
      - name: Check formatting with black
        run: black . --check
      # --- END OF FINAL FIX ---
