name: Scrape Latest CBE Data

on:
  workflow_dispatch:
  schedule:
    # القاعدة 1: التشغيل كل ساعة من 4 عصراً حتى 12 مساءً بتوقيت مصر، يومي الأحد والخميس
    # (توقيت UTC المقابل هو 13:00 إلى 21:00)
    - cron: '0 13-21 * * 0,4'
    
    # القاعدة 2: التشغيل مرة واحدة يومياً الساعة 8 صباحاً بتوقيت مصر كفحص احتياطي
    # (توقيت UTC المقابل هو 05:00)
    - cron: '0 5 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run data update script
        run: python update_data.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update CBE historical data [BOT]"
          file_pattern: cbe_historical_data.db
