name: Virus Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    name: ClamAV Virus Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run virus scan with the CORRECT action name
      # The 'D' in moonD4rk must be capitalized
      - name: Run virus scan on all files
        uses: moonD4rk/clamav-scan@v2
        with:
          fail-on-infected: 'true'
 
