name: Virus Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    name: ClamAV Virus Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run virus scan using a valid action
      # This is the corrected line
      - name: Run virus scan on all files
        uses: moonD4rk/clamav-scan@v2
        with:
          # This option ensures the workflow fails if an infected file is found
          fail-on-infected: 'true'
