name: Virus Scan

on:
  # يسمح بالتشغيل اليدوي من تبويب Actions
  workflow_dispatch:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    name: ClamAV Virus Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run virus scan on all files
        uses: moonD4rk/clamav-scan@v2
        with:
          fail-on-infected: 'true'
